# Generated by Django 6.0.3 on 2026-05-14 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteToTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_type', models.CharField(choices=[('INDIVIDUAL', 'Individual')], default='INDIVIDUAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'quote_to_tickets',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('folio', models.CharField(max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('estado', models.CharField(choices=[('DRAFT', 'Borrador'), ('SENT', 'Enviada'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada'), ('EXPIRED', 'Vencida'), ('CONVERTED', 'Convertida')], default='DRAFT', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('igv_rate', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('igv_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valido_hasta', models.DateField(blank=True, null=True)),
                ('condiciones', models.TextField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('is_active_version', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='quotes.quote')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotes', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='quotes', to='customers.customer')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='customers.device')),
                ('source_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='tickets.ticket')),
            ],
            options={
                'db_table': 'quotes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_type', models.CharField(choices=[('AMOUNT', 'Monto'), ('DISCOUNT', 'Descuento'), ('SPECIAL', 'Especial')], max_length=20)),
                ('required_level', models.CharField(choices=[('ADMIN', 'Administrador')], default='ADMIN', max_length=20)),
                ('estado', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada')], default='PENDING', max_length=20)),
                ('decidido_el', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decidido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_quote_approvals', to=settings.AUTH_USER_MODEL)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='quotes.quote')),
            ],
            options={
                'db_table': 'quote_approvals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(max_length=500, upload_to='quotes/attachments/%Y/%m/%d/')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('tamano_archivo', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='quotes.quote')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_quote_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quote_attachments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(choices=[('PRODUCT', 'Producto'), ('SERVICE', 'Servicio')], max_length=10)),
                ('descripcion', models.TextField()),
                ('cantidad', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento_linea', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_linea', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('supply_status', models.CharField(choices=[('NOT_APPLICABLE', 'No aplica'), ('RESERVED', 'Reservado'), ('OUT_OF_STOCK', 'Sin stock'), ('PENDING_ORDER', 'Orden pendiente')], default='NOT_APPLICABLE', max_length=20)),
                ('orden', models.IntegerField(default=0)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_lines', to='products.product')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='quotes.quote')),
            ],
            options={
                'db_table': 'quote_lines',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
