# Generated by Django 6.0.3 on 2026-05-14 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotes', '0001_initial'),
        ('services', '0001_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteline',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_lines', to='services.service'),
        ),
        migrations.AddField(
            model_name='quotetoticket',
            name='convertido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotetoticket',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_links', to='quotes.quote'),
        ),
        migrations.AddField(
            model_name='quotetoticket',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_links', to='tickets.ticket'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['folio'], name='quotes_folio_e9d4c4_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['customer'], name='quotes_custome_3e118e_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['estado'], name='quotes_estado_33454d_idx'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(fields=('folio', 'version'), name='unique_quote_folio_version'),
        ),
        migrations.AlterUniqueTogether(
            name='quotetoticket',
            unique_together={('quote', 'ticket')},
        ),
    ]
