# Generated by Django 6.0.3 on 2026-05-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='condiciones',
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_type',
            field=models.CharField(choices=[('REPAIR', 'Reparacion'), ('DIRECT', 'Directa')], default='REPAIR', max_length=20),
        ),
    ]
