# Generated by Django 6.0.3 on 2026-03-16 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'área',
                'verbose_name_plural': 'áreas',
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('business_name', models.CharField(max_length=150, verbose_name='nombre comercial')),
                ('legal_name', models.CharField(max_length=200, verbose_name='razón social')),
                ('ruc', models.CharField(max_length=20, verbose_name='RUC')),
                ('address', models.TextField(verbose_name='dirección')),
                ('phone', models.CharField(max_length=20, verbose_name='teléfono')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='WhatsApp / celular')),
                ('email', models.EmailField(max_length=254, verbose_name='correo electrónico')),
                ('website', models.URLField(blank=True, verbose_name='sitio web')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/logos/', verbose_name='logo')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='company/signatures/', verbose_name='firma')),
                ('cochera_grace_days', models.IntegerField(default=7, verbose_name='días de gracia cochera')),
                ('cochera_daily_rate', models.DecimalField(decimal_places=2, default=2.0, max_digits=12, verbose_name='tarifa diaria cochera')),
                ('quote_default_validity_days', models.IntegerField(default=15, verbose_name='días de validez cotizaciones')),
                ('quote_default_igv', models.DecimalField(decimal_places=2, default=18.0, max_digits=5, verbose_name='IGV por defecto (%)')),
                ('credit_grace_days', models.IntegerField(default=3, verbose_name='días de gracia tras vencimiento cuota')),
                ('credit_morosidad_limit', models.IntegerField(default=3, verbose_name='límite de veces en mora para Especial')),
            ],
            options={
                'verbose_name': 'perfil de empresa',
                'verbose_name_plural': 'perfil de empresa',
            },
        ),
        migrations.CreateModel(
            name='SubArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('max_capacity', models.IntegerField(blank=True, null=True, verbose_name='capacidad máxima')),
                ('current_load', models.IntegerField(default=0, verbose_name='carga actual')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'subárea',
                'verbose_name_plural': 'subáreas',
            },
        ),
    ]
