# Generated by Django 6.0.3 on 2026-05-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='quote_approval_threshold_amount',
            field=models.DecimalField(decimal_places=2, default=1500, max_digits=12),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='quote_default_igv',
            field=models.DecimalField(decimal_places=2, default=18, max_digits=5),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='quote_default_terms',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='quote_default_validity_days',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='foliocounter',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
