# Generated by Django 6.0.3 on 2026-03-16 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='actualizado por'),
        ),
        migrations.AddField(
            model_name='subarea',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subareas', to='core.area', verbose_name='área'),
        ),
        migrations.AlterUniqueTogether(
            name='subarea',
            unique_together={('area', 'name')},
        ),
    ]
