# Generated by Django 6.0.3 on 2026-05-14 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_companyprofile_quote_approval_threshold_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='cochera_daily_rate',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=12),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='cochera_grace_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='credit_grace_days',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='credit_morosidad_limit',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='legal_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_company_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Editar'), ('DELETE', 'Eliminar'), ('STATUS_CHANGE', 'Cambio de estado'), ('APPROVAL', 'Aprobacion'), ('PAYMENT', 'Pago'), ('SYSTEM', 'Sistema')], max_length=30)),
                ('module', models.CharField(max_length=80)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('object_id', models.CharField(blank=True, default='', max_length=100)),
                ('object_repr', models.CharField(blank=True, default='', max_length=255)),
                ('before_data', models.JSONField(blank=True, null=True)),
                ('after_data', models.JSONField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['module'], name='audit_logs_module_f52b4d_idx'), models.Index(fields=['model_name'], name='audit_logs_model_n_da6855_idx'), models.Index(fields=['created_at'], name='audit_logs_created_262184_idx')],
            },
        ),
    ]
