# Generated by Django 6.0.3 on 2026-04-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_foliocounter_alter_area_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subarea',
            name='area',
        ),
        migrations.RemoveField(
            model_name='foliocounter',
            name='prefix',
        ),
        migrations.AddField(
            model_name='foliocounter',
            name='document_type',
            field=models.CharField(default='TKT', max_length=10),
        ),
        migrations.AddField(
            model_name='foliocounter',
            name='year',
            field=models.IntegerField(default=2024),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='SubArea',
        ),
    ]
