# Generated by Django 6.0.3 on 2026-04-26 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_subarea_area_remove_foliocounter_prefix_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='foliocounter',
            unique_together={('document_type', 'year')},
        ),
    ]
