# Generated by Django 6.0.3 on 2026-04-28 18:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('OPEN', 'Abierta'), ('CLOSED', 'Cerrada')], default='OPEN', max_length=10)),
                ('opening_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('expected_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('declared_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('difference', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closing_notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cash_closures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cash_closures',
            },
        ),
        migrations.CreateModel(
            name='CocheraCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_date', models.DateField()),
                ('tarifa_diaria', models.DecimalField(decimal_places=2, max_digits=12)),
                ('esta_pagado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cochera_charges', to='tickets.ticket')),
            ],
            options={
                'db_table': 'cochera_charges',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_descuento', models.CharField(choices=[('PERCENTAGE', 'Porcentaje'), ('FIXED_AMOUNT', 'Monto Fijo')], max_length=20)),
                ('respuesta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazada')], default='PENDING', max_length=20)),
                ('decidido_el', models.DateTimeField(blank=True, null=True)),
                ('notas_admin', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decidido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_discounts', to=settings.AUTH_USER_MODEL)),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_discounts', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts', to='tickets.ticket')),
            ],
            options={
                'db_table': 'discounts',
            },
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('due_date', models.DateField()),
                ('fecha_venc_original', models.DateField()),
                ('esta_pagado', models.BooleanField(default=False)),
                ('pagado_el', models.DateTimeField(blank=True, null=True)),
                ('veces_reprogramada', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='tickets.ticket')),
            ],
            options={
                'db_table': 'payment_schedules',
            },
        ),
        migrations.CreateModel(
            name='PaymentScheduleReprogramacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_anterior', models.DateField()),
                ('fecha_nueva', models.DateField()),
                ('motivo', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reprogramaciones', to='finance.paymentschedule')),
                ('reprogramado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_schedule_reprogramaciones',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=20, unique=True)),
                ('tipo_recibo', models.CharField(choices=[('PAYMENT', 'Pago'), ('ADVANCE', 'Adelanto'), ('INSTALLMENT', 'Cuota')], default='PAYMENT', max_length=20)),
                ('metodo_pago', models.CharField(choices=[('CASH', 'Efectivo'), ('TRANSFER', 'Transferencia'), ('CARD', 'Tarjeta'), ('YAPE', 'Yape'), ('PLIN', 'Plin')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('referencia', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(choices=[('REGISTERED', 'Registrado'), ('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmado'), ('REJECTED', 'Rechazado'), ('REVERSED', 'Reversado')], default='REGISTERED', max_length=20)),
                ('conciliado_banco', models.BooleanField(default=False)),
                ('confirmado_el', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cash_closure', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='receipts', to='finance.cashclosure')),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_receipts', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_receipts', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='tickets.ticket')),
            ],
            options={
                'db_table': 'receipts',
            },
        ),
        migrations.CreateModel(
            name='PaymentVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(max_length=500, upload_to='tickets/vouchers/%Y/%m/%d/')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='finance.receipt')),
            ],
            options={
                'db_table': 'payment_vouchers',
            },
        ),
        migrations.CreateModel(
            name='PaymentReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reversa', models.CharField(choices=[('REVERSAL', 'Reversa'), ('REFUND', 'Reembolso'), ('CREDIT', 'Crédito')], max_length=20)),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=20)),
                ('aprobado_el', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reversals', to=settings.AUTH_USER_MODEL)),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_reversals', to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reversals', to='finance.receipt')),
            ],
            options={
                'db_table': 'payment_reversals',
            },
        ),
        migrations.CreateModel(
            name='ReceiptScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_aplicado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_items', to='finance.paymentschedule')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to='finance.receipt')),
            ],
            options={
                'db_table': 'receipt_schedule_items',
            },
        ),
        migrations.AddIndex(
            model_name='cashclosure',
            index=models.Index(fields=['user'], name='cash_closur_user_id_90e731_idx'),
        ),
        migrations.AddIndex(
            model_name='cashclosure',
            index=models.Index(fields=['estado'], name='cash_closur_estado_320700_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashclosure',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'OPEN')), fields=('user', 'estado'), name='unique_open_cash_closure_per_user'),
        ),
        migrations.AlterUniqueTogether(
            name='cocheracharge',
            unique_together={('ticket', 'charge_date')},
        ),
        migrations.AddIndex(
            model_name='paymentschedule',
            index=models.Index(fields=['ticket'], name='payment_sch_ticket__64232c_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentschedule',
            index=models.Index(fields=['due_date'], name='payment_sch_due_dat_71e7fb_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentschedule',
            index=models.Index(fields=['esta_pagado'], name='payment_sch_esta_pa_27fb1e_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['folio'], name='receipts_folio_d138a4_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['ticket'], name='receipts_ticket__8c58f9_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['estado'], name='receipts_estado_ba3e0a_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['cash_closure'], name='receipts_cash_cl_edb6f2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='receiptscheduleitem',
            unique_together={('receipt', 'cuota')},
        ),
    ]
