# Generated by Django 6.0.3 on 2026-05-17 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_quote_relationships(apps, schema_editor):
    Quote = apps.get_model('quotes', 'Quote')
    Receipt = apps.get_model('finance', 'Receipt')
    PaymentSchedule = apps.get_model('finance', 'PaymentSchedule')

    for receipt in Receipt.objects.filter(ticket__isnull=False, quote__isnull=True):
        quote = Quote.objects.filter(
            source_ticket_id=receipt.ticket_id,
            is_active_version=True,
        ).order_by('-version').first()
        if quote:
            receipt.quote_id = quote.id
            receipt.save(update_fields=['quote'])

    for schedule in PaymentSchedule.objects.filter(ticket__isnull=False, quote__isnull=True):
        quote = Quote.objects.filter(
            source_ticket_id=schedule.ticket_id,
            is_active_version=True,
        ).order_by('-version').first()
        if quote:
            schedule.quote_id = quote.id
            schedule.save(update_fields=['quote'])


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('quotes', '0003_remove_quote_condiciones_quote_quote_type'),
        ('tickets', '0003_checklisttemplate_checklisttemplateitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentschedule',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='quotes.quote'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='quotes.quote'),
        ),
        migrations.RunPython(backfill_quote_relationships, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='paymentschedule',
            index=models.Index(fields=['quote'], name='payment_sch_quote_i_7314a4_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['quote'], name='receipts_quote_i_dd6c5d_idx'),
        ),
    ]
