# Generated by Django 6.0.3 on 2026-05-14 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_alter_productsupplier_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=150)),
                ('ruc', models.CharField(max_length=20, unique=True)),
                ('contacto', models.CharField(blank=True, default='', max_length=150)),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('correo', models.EmailField(blank=True, default='', max_length=254)),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'suppliers',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('folio', models.CharField(max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('DRAFT', 'Borrador'), ('SENT', 'Enviada'), ('PARTIALLY_RECEIVED', 'Parcialmente recibida'), ('RECEIVED', 'Recibida'), ('CANCELLED', 'Cancelada')], default='DRAFT', max_length=30)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('destination_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='purchase_orders', to='products.warehouse')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='purchase_orders', to='suppliers.supplier')),
            ],
            options={
                'db_table': 'purchase_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_pedida', models.DecimalField(decimal_places=3, max_digits=12)),
                ('cantidad_recibida', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('serial_numbers', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='purchase_order_items', to='products.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='suppliers.purchaseorder')),
            ],
            options={
                'db_table': 'purchase_order_items',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, default='', max_length=30)),
                ('estado_nuevo', models.CharField(choices=[('DRAFT', 'Borrador'), ('SENT', 'Enviada'), ('PARTIALLY_RECEIVED', 'Parcialmente recibida'), ('RECEIVED', 'Recibida'), ('CANCELLED', 'Cancelada')], max_length=30)),
                ('motivo', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cambiado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_status_changes', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='suppliers.purchaseorder')),
            ],
            options={
                'db_table': 'purchase_order_status_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
