# Generated by Django 6.0.3 on 2026-03-16 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de eliminación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('customer_type', models.CharField(choices=[('PERSONA', 'Persona Natural'), ('EMPRESA', 'Empresa')], default='PERSONA', max_length=10, verbose_name='tipo de cliente')),
                ('identifier', models.CharField(max_length=20, unique=True, verbose_name='DNI/RUC')),
                ('name', models.CharField(max_length=150, verbose_name='nombre / razón social')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='dirección')),
                ('label', models.CharField(choices=[('NUEVO', 'Nuevo'), ('REGULAR', 'Regular'), ('FRECUENTE', 'Frecuente'), ('VIP', 'VIP'), ('MOROSO', 'Moroso'), ('ESPECIAL', 'Especial')], default='NUEVO', max_length=20, verbose_name='etiqueta')),
                ('previous_label', models.CharField(blank=True, max_length=20, verbose_name='etiqueta anterior')),
                ('times_moroso', models.IntegerField(default=0, verbose_name='veces moroso')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de eliminación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('device_type', models.CharField(max_length=50, verbose_name='tipo de equipo')),
                ('brand', models.CharField(max_length=80, verbose_name='marca')),
                ('model', models.CharField(max_length=120, verbose_name='modelo')),
                ('serial_number', models.CharField(blank=True, max_length=120, verbose_name='número de serie')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='customers.customer', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'dispositivo',
                'verbose_name_plural': 'dispositivos',
                'unique_together': {('customer', 'device_type', 'brand', 'model', 'serial_number')},
            },
        ),
    ]
