# Generated by Django 6.0.3 on 2026-04-28 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tipo_cliente', models.CharField(choices=[('PERSONA', 'Persona'), ('EMPRESA', 'Empresa')], default='PERSONA', max_length=10)),
                ('identificador', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('etiqueta', models.CharField(choices=[('NUEVO', 'Nuevo'), ('REGULAR', 'Regular'), ('FRECUENTE', 'Frecuente'), ('VIP', 'VIP'), ('MOROSO', 'Moroso'), ('ESPECIAL', 'Especial')], default='NUEVO', max_length=20)),
                ('etiqueta_anterior', models.CharField(blank=True, choices=[('NUEVO', 'Nuevo'), ('REGULAR', 'Regular'), ('FRECUENTE', 'Frecuente'), ('VIP', 'VIP'), ('MOROSO', 'Moroso'), ('ESPECIAL', 'Especial')], max_length=20, null=True)),
                ('veces_moroso', models.IntegerField(default=0)),
                ('notas', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customers',
                'indexes': [models.Index(fields=['nombre'], name='customers_nombre_53383f_idx'), models.Index(fields=['etiqueta'], name='customers_etiquet_6c971f_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('identificador',), name='unique_active_customer_identifier')],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tipo_equipo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=80)),
                ('modelo', models.CharField(max_length=120)),
                ('numero_serie', models.CharField(blank=True, max_length=120, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='devices', to='customers.customer')),
            ],
            options={
                'db_table': 'devices',
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('customer', 'tipo_equipo', 'marca', 'modelo', 'numero_serie'), name='unique_active_device_per_customer')],
            },
        ),
    ]
