# Generated by Django 6.0.3 on 2026-04-26 18:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('folio', models.CharField(max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('INTAKE', 'Ingreso'), ('DIAGNOSTIC', 'Diagnóstico'), ('QUOTED', 'Cotizado'), ('APPROVED', 'Aprobado'), ('WAITING_PARTS', 'En espera de repuesto'), ('IN_REPAIR', 'En reparación'), ('IN_TESTING', 'En pruebas'), ('READY', 'Listo'), ('DELIVERED', 'Entregado'), ('CLOSED', 'Cerrado'), ('REJECTED', 'Rechazado'), ('STORAGE', 'Cochera')], default='INTAKE', max_length=30)),
                ('prioridad', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='LOW', max_length=10)),
                ('descripcion_problema', models.TextField()),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('solucion', models.TextField(blank=True, null=True)),
                ('monto_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monto_aprobado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('es_garantia', models.BooleanField(default=False)),
                ('clave_consulta', models.CharField(blank=True, max_length=8, null=True)),
                ('entrega_estimada', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tickets', to='customers.customer')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='customers.device')),
                ('subarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='users.subarea')),
                ('ticket_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_garantia', to='tickets.ticket')),
            ],
            options={
                'db_table': 'tickets',
            },
        ),
        migrations.CreateModel(
            name='TicketAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('condicion', models.CharField(blank=True, max_length=50, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='tickets.ticket')),
            ],
            options={
                'db_table': 'ticket_accessories',
            },
        ),
        migrations.CreateModel(
            name='TicketEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(max_length=500, upload_to='tickets/evidencias/%Y/%m/%d/')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('tamano_archivo', models.IntegerField(blank=True, null=True)),
                ('tipo_archivo', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_evidences', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='tickets.ticket')),
            ],
            options={
                'db_table': 'ticket_evidences',
            },
        ),
        migrations.CreateModel(
            name='TicketTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, choices=[('INTAKE', 'Ingreso'), ('DIAGNOSTIC', 'Diagnóstico'), ('QUOTED', 'Cotizado'), ('APPROVED', 'Aprobado'), ('WAITING_PARTS', 'En espera de repuesto'), ('IN_REPAIR', 'En reparación'), ('IN_TESTING', 'En pruebas'), ('READY', 'Listo'), ('DELIVERED', 'Entregado'), ('CLOSED', 'Cerrado'), ('REJECTED', 'Rechazado'), ('STORAGE', 'Cochera')], max_length=30, null=True)),
                ('estado_nuevo', models.CharField(choices=[('INTAKE', 'Ingreso'), ('DIAGNOSTIC', 'Diagnóstico'), ('QUOTED', 'Cotizado'), ('APPROVED', 'Aprobado'), ('WAITING_PARTS', 'En espera de repuesto'), ('IN_REPAIR', 'En reparación'), ('IN_TESTING', 'En pruebas'), ('READY', 'Listo'), ('DELIVERED', 'Entregado'), ('CLOSED', 'Cerrado'), ('REJECTED', 'Rechazado'), ('STORAGE', 'Cochera')], max_length=30)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('fue_automatico', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cambiado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_transitions', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='tickets.ticket')),
            ],
            options={
                'db_table': 'ticket_transitions',
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['customer'], name='tickets_custome_321035_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_to'], name='tickets_assigne_cb12f9_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['estado'], name='tickets_estado_8017c6_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_at'], name='tickets_created_ed60df_idx'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('clave_consulta__isnull', False)), fields=('clave_consulta',), name='unique_clave_consulta_if_not_null'),
        ),
        migrations.AddIndex(
            model_name='tickettransition',
            index=models.Index(fields=['ticket'], name='ticket_tran_ticket__79958e_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettransition',
            index=models.Index(fields=['created_at'], name='ticket_tran_created_629165_idx'),
        ),
    ]
