# Generated by Django 6.0.3 on 2026-05-14 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('requerido', models.BooleanField(default=True)),
                ('completado', models.BooleanField(default=False)),
                ('notas', models.TextField(blank=True)),
                ('orden', models.IntegerField(default=0)),
                ('completado_el', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_ticket_checklists', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='tickets.ticket')),
            ],
            options={
                'db_table': 'ticket_checklist_items',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TicketChecklistEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(max_length=500, upload_to='tickets/checklists/%Y/%m/%d/')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_checklist_evidences', to=settings.AUTH_USER_MODEL)),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='tickets.ticketchecklistitem')),
            ],
            options={
                'db_table': 'ticket_checklist_evidences',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketSubareaMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_subarea_movements', to=settings.AUTH_USER_MODEL)),
                ('subarea_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_moved_to', to='users.subarea')),
                ('subarea_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_moved_from', to='users.subarea')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subarea_movements', to='tickets.ticket')),
            ],
            options={
                'db_table': 'ticket_subarea_movements',
                'ordering': ['-created_at'],
            },
        ),
    ]
