# Generated by Django 6.0.3 on 2026-05-14 18:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='costo_promedio',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='reservado',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='products.warehouse'),
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('ENTRY', 'Entrada'), ('EXIT', 'Salida'), ('TRANSFER_OUT', 'Transferencia salida'), ('TRANSFER_IN', 'Transferencia entrada'), ('ADJUSTMENT_IN', 'Ajuste entrada'), ('ADJUSTMENT_OUT', 'Ajuste salida'), ('RETURN', 'Devolución')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('serial_numbers', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to=settings.AUTH_USER_MODEL)),
                ('destination_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='incoming_inventory_movements', to='products.warehouse')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='inventory_movements', to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='inventory_movements', to='products.warehouse')),
            ],
            options={
                'db_table': 'inventory_movements',
                'indexes': [models.Index(fields=['product'], name='inventory_m_product_9a9eef_idx'), models.Index(fields=['warehouse'], name='inventory_m_warehou_3611e7_idx'), models.Index(fields=['movement_type'], name='inventory_m_movemen_a3c722_idx'), models.Index(fields=['created_at'], name='inventory_m_created_c2f39c_idx'), models.Index(fields=['reference_type', 'reference_id'], name='inventory_m_referen_ce9f4f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.BigIntegerField()),
                ('supplier_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lead_time_days', models.IntegerField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_suppliers', to='products.product')),
            ],
            options={
                'db_table': 'product_suppliers',
                'unique_together': {('product', 'supplier_id')},
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12)),
                ('estado', models.CharField(choices=[('ACTIVE', 'Activa'), ('CONSUMED', 'Consumida'), ('RELEASED', 'Liberada')], default='ACTIVE', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('consumido_el', models.DateTimeField(blank=True, null=True)),
                ('liberado_el', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_reservations', to=settings.AUTH_USER_MODEL)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reservations', to='products.stockitem')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stock_reservations', to='tickets.ticket')),
            ],
            options={
                'db_table': 'stock_reservations',
                'indexes': [models.Index(fields=['ticket'], name='stock_reser_ticket__aca8a1_idx'), models.Index(fields=['stock_item'], name='stock_reser_stock_i_5344a4_idx'), models.Index(fields=['estado'], name='stock_reser_estado_fa7f71_idx')],
            },
        ),
    ]
