# Generated by Django 6.0.3 on 2026-05-14 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_stockitem_costo_promedio_stockitem_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productsupplier',
            unique_together=set(),
        ),
    ]
