# Generated by Django 6.0.3 on 2026-05-14 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productsupplier_unique_together'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsupplier',
            old_name='supplier_id',
            new_name='supplier_id_legacy',
        ),
        migrations.AddField(
            model_name='productsupplier',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_suppliers', to='suppliers.supplier'),
        ),
        migrations.AlterField(
            model_name='productsupplier',
            name='supplier_id_legacy',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='productsupplier',
            constraint=models.UniqueConstraint(condition=models.Q(('supplier__isnull', False)), fields=('product', 'supplier'), name='unique_product_supplier_when_supplier_present'),
        ),
    ]
